services:
  - type: web
    name: fxwave_signals_mt5
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    autoDeploy: true
